app = "cubis-fly-dns"

kill_signal = "SIGINT"
kill_timeout = 2

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[env]
  DNS_SERVER_DOMAIN = "cubis-fly-dns"

[[services]]
  internal_port = 53
  processes = ["app"]
  protocol = "udp"

  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 100

  [[services.ports]]
    port = "53"
  
  [[services.ports]]
    port = "53"
    protocol = "udp"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
