on:
  schedule:
    - cron: 0 3 * * 3
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run script
        run: ./gh-build.sh
        shell: bash
