on:
  schedule:
    - cron: 0 3 * * 3
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Run script
        run: ./gh-build.sh
        shell: bash
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
